refactor get item
DevOps-Agile-Squad/orders pull request #125
Opened 2021-08-09 05:15 UTC by JoanneWooW

2021-08-09 05:51 UTC, pkutlesa commented on service/routes.py
> +            raise NotFound(f"Order with id {order_id} was not found")
abort(status.HTTP_404_NOT_FOUND, "Request for item with id {item_id} in order {order_id}")

2021-08-09 05:52 UTC, pkutlesa commented on service/routes.py
> +            raise NotFound(f"Item with id {item_id} was not found in order {order_id}")
abort(status.HTTP_404_NOT_FOUND, "Item with id {item_id} was not found in order {order_id}")

2021-08-09 05:53 UTC, pkutlesa requested changes
Nice! Just left small comments on lines 321 and 325

2021-08-09 06:38 UTC, JoanneWooW commented
@pkutlesa Nice catch, thank you! Fixed!

2021-08-09 07:24 UTC, pkutlesa commented
close! just remove the letter f before the quotations on lines 321 and 325

2021-08-09 08:09 UTC, JoanneWooW commented
@pkutlesa Thanks for pointing out! Could you explain why I should not use 'f' in front of quotations? I thought you missed them by accident so I added them on...

2021-08-09 17:28 UTC, pkutlesa commented
My first impression was that they were causing tests to fail until I read your most recent update. f-strings should be fine :)

2021-08-10 04:12 UTC, pkutlesa approved these changes
LGTM!

2021-08-10 05:36 UTC, merged

2021-08-10 06:10 UTC, pkutlesa commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036 "deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036") to [prod](https://console.bluemix.net/apps/f43af9cd-c881-41ff-b5bd-1ee109712701?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:prod"), including commit b139f576276b790d30c2d4f0a9c3c71297197e79